# docker-compose file for setting up pretix in docker environment
# author: gregor
# date: 2019-03-13

version: '2'
services:

  # copy of mattermost setup
  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=pretix-dbuser
      - POSTGRES_PASSWORD=pretix-dbuser-password
      - POSTGRES_DB=pretix
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1
    networks:
      jh-pretix-net:
        aliases:
          - db

  redis:
    image: quay.io/sameersbn/redis:latest
    restart: unless-stopped
    networks:
      jh-pretix-net:
        aliases:
          - redis

  pretix:
    image: pretix/standalone:stable
    restart: unless-stopped
    volumes:
      - ./volumes/pretix-data:/data
      - ./volumes/pretix:/etc/pretix
    ports:
      - 127.0.0.1:5000:80
    networks:
      jh-pretix-net:
        aliases:
          - pretix

networks:
  jh-pretix-net:
